### ISSUE TITLE
Getting "undefined" when script tries to generate download links

### ISSUE THREAD

**Issue by RutgerM** [Vergo777/Kissanime-LinkDownload#6]
I haven't used your script for a week or so, so I'm not sure if it's just today or has been going on for a while now.

Anyone else having this same problem?

**Comment by Vergo777** [comment]
Hey @RutgerM, this is probably because the application has hit the monthly limit for the link shortening service I'm using. 

To be honest I haven't updated this app in ages and I'm so incredibly busy right now that I won't have time to make any changes, so you might be better off using one of the forks from now on where a lot of recent developments have taken place. This one looks quite promising to me, might be worth giving it a go! - https://github.com/Amraki/KissAnime-DLC

**Comment by RutgerM** [comment]
@Vergo777: Aha, I see. I'll go check out the fork then. Thanks for the help and the link!

**Comment by mysticpoisen** [comment]
I've been using this one, it's much easier to use in my opinion at least.
This isn't a fork, it's entirely it's own thing.

https://github.com/arasyi/KissAnime-DTA

**Comment by RutgerM** [comment]
@mysticpoisen: I've tried out that script too, but the button isn't showing up for me as it's supposed to do in this example: https://arasyi.github.io/KissAnime-DTA/.
